# Lesson 2 Lab:  Practical Pandas

_This is a quiz given in Roger Peng's [Coursera](https://www.coursera.org) class [Computing for Data Analysis](https://www.coursera.org/course/compdata).  _

_Sourced from [Research Computing MeetUp's](https://github.com/ResearchComputing/Meetup-Fall-2013) Python course._

In [9]:
import pandas as pd

data = pd.read_csv('ozone.csv')

In [10]:
print data.head()

   Ozone  Solar.R  Wind  Temp  Month  Day
0   41.0    190.0   7.4    67      5    1
1   36.0    118.0   8.0    72      5    2
2   12.0    149.0  12.6    74      5    3
3   18.0    313.0  11.5    62      5    4
4    NaN      NaN  14.3    56      5    5

Print the column names of the dataset to the screen, one column name per line.

In [43]:
print data.head(0)

Empty DataFrame
Columns: [Ozone, Solar.R, Wind, Temp, Month, Day]
Index: []

In [46]:
data.loc[0]

Ozone       41.0
Solar.R    190.0
Wind         7.4
Temp        67.0
Month        5.0
Day          1.0
Name: 0, dtype: float64

Extract the first 2 rows of the data frame and print them to the console. What does the output
look like?

In [47]:
data[['Ozone', 'Solar.R']]

     Ozone  Solar.R
0     41.0    190.0
1     36.0    118.0
2     12.0    149.0
3     18.0    313.0
4      NaN      NaN
5     28.0      NaN
6     23.0    299.0
7     19.0     99.0
8      8.0     19.0
9      NaN    194.0
10     7.0      NaN
11    16.0    256.0
12    11.0    290.0
13    14.0    274.0
14    18.0     65.0
15    14.0    334.0
16    34.0    307.0
17     6.0     78.0
18    30.0    322.0
19    11.0     44.0
20     1.0      8.0
21    11.0    320.0
22     4.0     25.0
23    32.0     92.0
24     NaN     66.0
25     NaN    266.0
26     NaN      NaN
27    23.0     13.0
28    45.0    252.0
29   115.0    223.0
..     ...      ...
123   96.0    167.0
124   78.0    197.0
125   73.0    183.0
126   91.0    189.0
127   47.0     95.0
128   32.0     92.0
129   20.0    252.0
130   23.0    220.0
131   21.0    230.0
132   24.0    259.0
133   44.0    236.0
134   21.0    259.0
135   28.0    238.0
136    9.0     24.0
137   13.0    112.0
138   46.0    237.0
139   18.0    224.0
140   13.0     27.0
141   24.0    238.0
142   16.0    201.0
143   13.0    238.0
144   23.0     14.0
145   36.0    139.0
146    7.0     49.0
147   14.0     20.0
148   30.0    193.0
149    NaN    145.0
150   14.0    191.0
151   18.0    131.0
152   20.0    223.0

[153 rows x 2 columns]

How many observations (i.e. rows) are in this data frame?

In [51]:
len(data)

153

Extract the last 2 rows of the data frame and print them to the console. What does the output
look like?

In [52]:
data.tail(2)

     Ozone  Solar.R  Wind  Temp  Month  Day
151   18.0    131.0   8.0    76      9   29
152   20.0    223.0  11.5    68      9   30

What is the value of Ozone in the 47th row?

In [63]:
data.iloc[47]

Ozone       37.0
Solar.R    284.0
Wind        20.7
Temp        72.0
Month        6.0
Day         17.0
Name: 47, dtype: float64

In [126]:
data.loc['Ozone'].47

SyntaxError: invalid syntax (<ipython-input-126-d50f381d4a0c>, line 1)

How many missing values are in the Ozone column of this data frame?

In [90]:
pd.isnull(data)

     Ozone Solar.R   Wind   Temp  Month    Day
0    False   False  False  False  False  False
1    False   False  False  False  False  False
2    False   False  False  False  False  False
3    False   False  False  False  False  False
4     True    True  False  False  False  False
5    False    True  False  False  False  False
6    False   False  False  False  False  False
7    False   False  False  False  False  False
8    False   False  False  False  False  False
9     True   False  False  False  False  False
10   False    True  False  False  False  False
11   False   False  False  False  False  False
12   False   False  False  False  False  False
13   False   False  False  False  False  False
14   False   False  False  False  False  False
15   False   False  False  False  False  False
16   False   False  False  False  False  False
17   False   False  False  False  False  False
18   False   False  False  False  False  False
19   False   False  False  False  False  False
20   False   False  False  False  False  False
21   False   False  False  False  False  False
22   False   False  False  False  False  False
23   False   False  False  False  False  False
24    True   False  False  False  False  False
25    True   False  False  False  False  False
26    True    True  False  False  False  False
27   False   False  False  False  False  False
28   False   False  False  False  False  False
29   False   False  False  False  False  False
..     ...     ...    ...    ...    ...    ...
123  False   False  False  False  False  False
124  False   False  False  False  False  False
125  False   False  False  False  False  False
126  False   False  False  False  False  False
127  False   False  False  False  False  False
128  False   False  False  False  False  False
129  False   False  False  False  False  False
130  False   False  False  False  False  False
131  False   False  False  False  False  False
132  False   False  False  False  False  False
133  False   False  False  False  False  False
134  False   False  False  False  False  False
135  False   False  False  False  False  False
136  False   False  False  False  False  False
137  False   False  False  False  False  False
138  False   False  False  False  False  False
139  False   False  False  False  False  False
140  False   False  False  False  False  False
141  False   False  False  False  False  False
142  False   False  False  False  False  False
143  False   False  False  False  False  False
144  False   False  False  False  False  False
145  False   False  False  False  False  False
146  False   False  False  False  False  False
147  False   False  False  False  False  False
148  False   False  False  False  False  False
149   True   False  False  False  False  False
150  False   False  False  False  False  False
151  False   False  False  False  False  False
152  False   False  False  False  False  False

[153 rows x 6 columns]

In [87]:
data.Ozone.isnull()

0      False
1      False
2      False
3      False
4       True
5      False
6      False
7      False
8      False
9       True
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24      True
25      True
26      True
27     False
28     False
29     False
       ...
123    False
124    False
125    False
126    False
127    False
128    False
129    False
130    False
131    False
132    False
133    False
134    False
135    False
136    False
137    False
138    False
139    False
140    False
141    False
142    False
143    False
144    False
145    False
146    False
147    False
148    False
149     True
150    False
151    False
152    False
Name: Ozone, dtype: bool

What is the mean of the Ozone column in this dataset? Exclude missing values (coded as NA)
from this calculation.

In [95]:
data=data.dropna()
data[['Ozone']]
data.mean()

Ozone       42.099099
Solar.R    184.801802
Wind         9.939640
Temp        77.792793
Month        7.216216
Day         15.945946
dtype: float64

Extract the subset of rows of the data frame where Ozone values are above 31 and Temp values
are above 90. What is the mean of Solar.R in this subset?

In [99]:
data[(data.Ozone>31)]

     Ozone  Solar.R  Wind  Temp  Month  Day
0     41.0    190.0   7.4    67      5    1
1     36.0    118.0   8.0    72      5    2
16    34.0    307.0  12.0    66      5   17
23    32.0     92.0  12.0    61      5   24
28    45.0    252.0  14.9    81      5   29
29   115.0    223.0   5.7    79      5   30
30    37.0    279.0   7.4    76      5   31
39    71.0    291.0  13.8    90      6    9
40    39.0    323.0  11.5    87      6   10
47    37.0    284.0  20.7    72      6   17
61   135.0    269.0   4.1    84      7    1
62    49.0    248.0   9.2    85      7    2
63    32.0    236.0   9.2    81      7    3
65    64.0    175.0   4.6    83      7    5
66    40.0    314.0  10.9    83      7    6
67    77.0    276.0   5.1    88      7    7
68    97.0    267.0   6.3    92      7    8
69    97.0    272.0   5.7    92      7    9
70    85.0    175.0   7.4    89      7   10
76    48.0    260.0   6.9    81      7   16
77    35.0    274.0  10.3    82      7   17
78    61.0    285.0   6.3    84      7   18
79    79.0    187.0   5.1    87      7   19
80    63.0    220.0  11.5    85      7   20
84    80.0    294.0   8.6    86      7   24
85   108.0    223.0   8.0    85      7   25
87    52.0     82.0  12.0    86      7   27
88    82.0    213.0   7.4    88      7   28
89    50.0    275.0   7.4    86      7   29
90    64.0    253.0   7.4    83      7   30
91    59.0    254.0   9.2    81      7   31
92    39.0     83.0   6.9    81      8    1
98   122.0    255.0   4.0    89      8    7
99    89.0    229.0  10.3    90      8    8
100  110.0    207.0   8.0    90      8    9
103   44.0    192.0  11.5    86      8   12
105   65.0    157.0   9.7    80      8   14
108   59.0     51.0   6.3    79      8   17
111   44.0    190.0  10.3    78      8   20
115   45.0    212.0   9.7    79      8   24
116  168.0    238.0   3.4    81      8   25
117   73.0    215.0   8.0    86      8   26
119   76.0    203.0   9.7    97      8   28
120  118.0    225.0   2.3    94      8   29
121   84.0    237.0   6.3    96      8   30
122   85.0    188.0   6.3    94      8   31
123   96.0    167.0   6.9    91      9    1
124   78.0    197.0   5.1    92      9    2
125   73.0    183.0   2.8    93      9    3
126   91.0    189.0   4.6    93      9    4
127   47.0     95.0   7.4    87      9    5
128   32.0     92.0  15.5    84      9    6
133   44.0    236.0  14.9    81      9   11
138   46.0    237.0   6.9    78      9   16
145   36.0    139.0  10.3    81      9   23

In [105]:
data=data[(data.Ozone>31)&(data.Temp>90)]
data

     Ozone  Solar.R  Wind  Temp  Month  Day
68    97.0    267.0   6.3    92      7    8
69    97.0    272.0   5.7    92      7    9
119   76.0    203.0   9.7    97      8   28
120  118.0    225.0   2.3    94      8   29
121   84.0    237.0   6.3    96      8   30
122   85.0    188.0   6.3    94      8   31
123   96.0    167.0   6.9    91      9    1
124   78.0    197.0   5.1    92      9    2
125   73.0    183.0   2.8    93      9    3
126   91.0    189.0   4.6    93      9    4

In [106]:
data.mean()

Ozone       89.5
Solar.R    212.8
Wind         5.6
Temp        93.4
Month        8.2
Day         14.5
dtype: float64

What is the mean of "Temp" when "Month" is equal to 6?

In [113]:
data = pd.read_csv('ozone.csv')

In [114]:
data

     Ozone  Solar.R  Wind  Temp  Month  Day
0     41.0    190.0   7.4    67      5    1
1     36.0    118.0   8.0    72      5    2
2     12.0    149.0  12.6    74      5    3
3     18.0    313.0  11.5    62      5    4
4      NaN      NaN  14.3    56      5    5
5     28.0      NaN  14.9    66      5    6
6     23.0    299.0   8.6    65      5    7
7     19.0     99.0  13.8    59      5    8
8      8.0     19.0  20.1    61      5    9
9      NaN    194.0   8.6    69      5   10
10     7.0      NaN   6.9    74      5   11
11    16.0    256.0   9.7    69      5   12
12    11.0    290.0   9.2    66      5   13
13    14.0    274.0  10.9    68      5   14
14    18.0     65.0  13.2    58      5   15
15    14.0    334.0  11.5    64      5   16
16    34.0    307.0  12.0    66      5   17
17     6.0     78.0  18.4    57      5   18
18    30.0    322.0  11.5    68      5   19
19    11.0     44.0   9.7    62      5   20
20     1.0      8.0   9.7    59      5   21
21    11.0    320.0  16.6    73      5   22
22     4.0     25.0   9.7    61      5   23
23    32.0     92.0  12.0    61      5   24
24     NaN     66.0  16.6    57      5   25
25     NaN    266.0  14.9    58      5   26
26     NaN      NaN   8.0    57      5   27
27    23.0     13.0  12.0    67      5   28
28    45.0    252.0  14.9    81      5   29
29   115.0    223.0   5.7    79      5   30
..     ...      ...   ...   ...    ...  ...
123   96.0    167.0   6.9    91      9    1
124   78.0    197.0   5.1    92      9    2
125   73.0    183.0   2.8    93      9    3
126   91.0    189.0   4.6    93      9    4
127   47.0     95.0   7.4    87      9    5
128   32.0     92.0  15.5    84      9    6
129   20.0    252.0  10.9    80      9    7
130   23.0    220.0  10.3    78      9    8
131   21.0    230.0  10.9    75      9    9
132   24.0    259.0   9.7    73      9   10
133   44.0    236.0  14.9    81      9   11
134   21.0    259.0  15.5    76      9   12
135   28.0    238.0   6.3    77      9   13
136    9.0     24.0  10.9    71      9   14
137   13.0    112.0  11.5    71      9   15
138   46.0    237.0   6.9    78      9   16
139   18.0    224.0  13.8    67      9   17
140   13.0     27.0  10.3    76      9   18
141   24.0    238.0  10.3    68      9   19
142   16.0    201.0   8.0    82      9   20
143   13.0    238.0  12.6    64      9   21
144   23.0     14.0   9.2    71      9   22
145   36.0    139.0  10.3    81      9   23
146    7.0     49.0  10.3    69      9   24
147   14.0     20.0  16.6    63      9   25
148   30.0    193.0   6.9    70      9   26
149    NaN    145.0  13.2    77      9   27
150   14.0    191.0  14.3    75      9   28
151   18.0    131.0   8.0    76      9   29
152   20.0    223.0  11.5    68      9   30

[153 rows x 6 columns]

In [123]:
data=data[(data.Month>5)&(data.Month<7)]
data

AttributeError: 'list' object has no attribute 'Month'

In [2]:
data=data.Month==6

SyntaxError: invalid syntax (<ipython-input-2-891b9d9f298c>, line 1)

What was the maximum ozone value in the month of May (i.e. Month = 5)?

In [ ]:
I can't get the previous one to work so no go for this'

# Next Steps

**Recommended Resources**

Name | Description
--- | ---
[Official Pandas Tutorials](http://pandas.pydata.org/pandas-docs/stable/tutorials.html) | Wes & Company's selection of tutorials and lectures
[Julia Evans Pandas Cookbook](https://github.com/jvns/pandas-cookbook) | Great resource with eamples from weather, bikes and 311 calls
[Learn Pandas Tutorials](https://bitbucket.org/hrojas/learn-pandas) | A great series of Pandas tutorials from Dave Rojas
[Research Computing Python Data PYNBs](https://github.com/ResearchComputing/Meetup-Fall-2013/tree/master/python) | A super awesome set of python notebooks from a meetup-based course exclusively devoted to pandas